image:
  file: .gitpod.dockerfile
ports:
- port: 27017 # mongodb
  onOpen: ignore
  
tasks:
  - name: db
    command: |
      mkdir -p /workspace/data
      mongod --dbpath /workspace/data

vscode:
  extensions:
    - svelte.svelte-vscode
    
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
