image:
  file: .gitpod.dockerfile
ports:
- port: 27017 # mongodb
  onOpen: ignore
  
tasks:
  - init: npm install
    command: npm run dev
  - name: db
    # starting mongo in background, so it doesn't block prebuilds
    before: >
      mkdir -p /workspace/data &&
      (mongod --dbpath /workspace/data &)

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true