image:
  file: .gitpod.dockerfile
  
ports:
  - port: 27017 # mongodb
    onOpen: ignore
  - port: 5000
    onopen: open-preview
  - port: 35729
    onopen: ignore
  
tasks:
  - name: db
    command: |
      mkdir -p /workspace/data
      mongod --dbpath /workspace/data
    
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
